SELECT * FROM beststore.products;

INSERT INTO products (
name, brand, category, price, description, image_file_name, create_at
)
VALUES
('Apple iPhone 15 Pro Max', 'Apple', 'Phones', 7.932, 'O Apple iPhone 15 Pro Max é um smartphone iOS com características inovadoras que o tornam uma excelente opção para qualquer tipo de utilização, representando um dos melhores dispositivos móveis já feitos. A tela de 6.7 polegadas coloca esse Apple no topo de sua categoria. A resolução também é alta: 2796x1290 pixel. As funcionalidades oferecidas pelo Apple iPhone 15 Pro Max são muitas e todas top de linha. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS presente no aparelho. Tem também leitor multimídia, videoconferência, e bluetooth. Enfatizamos a excelente memória interna de 1024 GB mas sem a possibilidade de expansão.
A excelência deste Apple iPhone 15 Pro Max é completada por uma câmera de 48 megapixels que permite tirar fotos fantásticas com uma resolução de 8000x6000 pixels e gravar vídeos em 4K a espantosa resolução de 3840x2160 pixels. A espessura de 8.3 milímetros é realmente ótima e torna o Apple iPhone 15 Pro Max ainda mais espetacular.', 'Iphone-15-Pro-Max.jpg', CURRENT_TIMESTAMP),
('Apple iPhone 14 Pro Max', 'Apple', 'Phones', 8.199, 'O Apple iPhone 14 Pro Max é um smartphone iOS com características inovadoras que o tornam uma excelente opção para qualquer tipo de utilização, representando um dos melhores dispositivos móveis já feitos. A tela de 6.7 polegadas coloca esse Apple no topo de sua categoria. A resolução também é alta: 2796x1290 pixel. As funcionalidades oferecidas pelo Apple iPhone 14 Pro Max são muitas e todas top de linha. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS presente no aparelho. Tem também leitor multimídia, videoconferência, e bluetooth. Enfatizamos a excelente memória interna de 1000 GB mas sem a possibilidade de expansão.
A excelência deste Apple iPhone 14 Pro Max é completada por uma câmera de 48 megapixels que permite tirar fotos fantásticas com uma resolução de 8000x6000 pixels e gravar vídeos em 4K a espantosa resolução de 3840x2160 pixels. A espessura de apenas 7.9 milímetros torna o Apple iPhone 14 Pro Max um dos telefones mais finos que existem.', 'Iphone-14-Pro-Max.jpg', CURRENT_TIMESTAMP),
('Apple iPhone 13 Pro Max', 'Apple', 'Phones', 9.498, 'O Apple iPhone 13 Pro Max é um dos smartphones iOS mais avançados e completos que existem em circulação. Tem um grande display de 6.7 polegadas com uma resolução de 2778x1284 pixel. As funcionalidades oferecidas pelo Apple iPhone 13 Pro Max são muitas e inovadoras. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet. Enfatizamos a excelente memória interna de 1000 GB mas sem a possibilidade de expansão.
Câmera discreta de 12 megapixel mas que permite ao Apple iPhone 13 Pro Max tirar fotos de boa qualidade com uma resolução de 4000x3000 pixel e gravar vídeos em 4K a espantosa resolução de 3840x2160 pixels. A espessura de 7.7mm torna o Apple iPhone 13 Pro Max um dos telefones mais completos e finos', 'Iphone-13-Pro-Max.jpg', CURRENT_TIMESTAMP),
('Apple iPhone 12 Pro', 'Apple', 'Phones', 4.024 , 'O Apple iPhone 12 Pro é um dos smartphones iOS mais avançados e completos que existem em circulação. Tem um grande display de 6.1 polegadas com uma resolução de 2532x1170 pixel. As funcionalidades oferecidas pelo Apple iPhone 12 Pro são muitas e inovadoras. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet. Enfatizamos a excelente memória interna de 512 GB mas sem a possibilidade de expansão.
Câmera discreta de 12 megapixel mas que permite ao Apple iPhone 12 Pro tirar fotos de boa qualidade com uma resolução de 4000x3000 pixel e gravar vídeos em 4K a espantosa resolução de 3840x2160 pixels. A espessura de 7.4mm torna o Apple iPhone 12 Pro um dos telefones mais completos e finos.', 'Iphone-12-Pro.jpg', CURRENT_TIMESTAMP),
('Samsung Galaxy S24 Ultra', 'Samsung', 'Phones', 8.500, 'O Samsung Galaxy S24 Ultra é um smartphone Android com características inovadoras que o tornam uma excelente opção para qualquer tipo de utilização, representando um dos melhores dispositivos móveis já feitos. A tela de 6.8 polegadas coloca esse Samsung no topo de sua categoria. Além disso a resolução é das mais altas atualmente em circulação: 3088x1440 pixel. As funcionalidades oferecidas pelo Samsung Galaxy S24 Ultra são muitas e todas top de linha. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS presente no aparelho. Tem também leitor multimídia, videoconferência, e bluetooth. Enfatizamos a excelente memória interna de 1024 GB mas sem a possibilidade de expansão.
A excelência deste Samsung Galaxy S24 Ultra é completada por uma câmera de 200 megapixels que permite tirar fotos fantásticas com uma resolução de 46330x12247 pixels e gravar vídeos em 8K a espantosa resolução de 7680x4320 pixels. A espessura de 8.6 milímetros é realmente ótima e torna o Samsung Galaxy S24 Ultra ainda mais espetacular.', 'Samsung-Galaxy-S24-Ultra.jpg', CURRENT_TIMESTAMP),
('Redmi Note 13 4G', 'Redmi', 'Phones', 1.399, 'O Redmi Note 13 4G é um smartphone Android avançado e abrangente em todos os pontos de vista com algumas características excelentes. Tem uma grande tela de 6.67 polegadas com uma resolução de 2400x1080 pixels. As funcionalidades oferecidas pelo Redmi Note 13 4G são muitas e inovadoras. Começando pelo LTE 4G que permite a transferência de dados e excelente navegação na internet. Enfatizamos a excelente memória interna de 128 GB com a possibilidade de expansão.
O Redmi Note 13 4G é um produto com poucos concorrentes em termos de multimídia graças à câmera de 108 megapixels que permite ao Redmi Note 13 4G tirar fotos fantásticas com uma resolução de 12000x9000 pixels e gravar vídeos em alta definição (Full HD) com uma resolução de 1920x1080 pixels. Muito fino, 8 milímetros, o que torna o Redmi Note 13 4G realmente interessante.', 'Redmi-Note-13-4G.jpg', CURRENT_TIMESTAMP),
('Motorola Moto G34', 'Motorola', 'Phones', 1.299, 'O Motorola Moto G34 é um smartphone Android de bom nível, ótimo para fotos, que pode satisfazer até o mais exigente dos usuários. Tem uma enorme tela Touchscreen de 6.5 polegadas com uma resolução de 1600x720 pixel que não é das mais elevadas. Sobre as características deste Motorola Moto G34 na verdade não falta nada. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS. Tem também leitor multimídia, videoconferência e bluetooth. Enfatizamos a boa memória interna de 256 GB com a possibilidade de expansão.
O Motorola Moto G34 é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Motorola Moto G34 tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em alta definição (Full HD) com uma resolução de 1920x1080 pixels. Muito fino, 8 milímetros, o que torna o Motorola Moto G34 realmente interessante.', 'Motorola-moto-g34-5g.jpg', CURRENT_TIMESTAMP),
('Samsung Galaxy S22 (Exynos)', 'Samsung', 'Phones', 2.975, 'O Samsung Galaxy S22 (Exynos) é um smartphone Android avançado e abrangente em todos os pontos de vista com algumas características excelentes. Tem uma grande tela de 6.1 polegadas com uma resolução de 2340x1080 pixels. As funcionalidades oferecidas pelo Samsung Galaxy S22 (Exynos) são muitas e inovadoras. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet. Enfatizamos a excelente memória interna de 256 GB mas sem a possibilidade de expansão.
O Samsung Galaxy S22 (Exynos) é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Samsung Galaxy S22 (Exynos) tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em 8K a espantosa resolução de 7680x4320 pixels. Muito fino, 7.6 milímetros, o que torna o Samsung Galaxy S22 (Exynos) realmente interessante.', 'Samsung-Galaxy-S22-Exynos.jpg', CURRENT_TIMESTAMP),
('realme C67', 'realme', 'Phones', 1.169, 'O realme C67 é um smartphone Android de bom nível, ótimo para fotos, que pode satisfazer até o mais exigente dos usuários. Tem uma enorme tela Touchscreen de 6.72 polegadas com uma resolução de 2400x1080 pixel. Sobre as características deste realme C67 na verdade não falta nada. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS. Tem também leitor multimídia, videoconferência e bluetooth. Enfatizamos a boa memória interna de 128 GB com a possibilidade de expansão.
O realme C67 é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao realme C67 tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em alta definição (Full HD) com uma resolução de 1920x1080 pixels. Muito fino, 7.9 milímetros, o que torna o realme C67 realmente interessante.', 'realme-C67.jpg', CURRENT_TIMESTAMP),
('Samsung Galaxy A25', 'Samsung', 'Phones', 2.099, 'O Samsung Galaxy A25 é um smartphone Android avançado e abrangente em todos os pontos de vista com algumas características excelentes. Tem uma grande tela de 6.5 polegadas com uma resolução de 2340x1080 pixels. As funcionalidades oferecidas pelo Samsung Galaxy A25 são muitas e inovadoras. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet. Enfatizamos a excelente memória interna de 128 GB com a possibilidade de expansão.
O Samsung Galaxy A25 é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Samsung Galaxy A25 tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em 4K a espantosa resolução de 3840x2160 pixels. Muito fino, 8.3 milímetros, o que torna o Samsung Galaxy A25 realmente interessante', 'Samsung-Galaxy-A25.jpg', CURRENT_TIMESTAMP),
('Samsung Galaxy A15 5G', 'Samsung', 'Phones', 1.699, 'O Samsung Galaxy A15 5G é um smartphone Android de bom nível, ótimo para fotos, que pode satisfazer até o mais exigente dos usuários. Tem uma enorme tela Touchscreen de 6.5 polegadas com uma resolução de 2340x1080 pixel. Sobre as características deste Samsung Galaxy A15 5G na verdade não falta nada. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS. Tem também leitor multimídia, videoconferência e bluetooth. Enfatizamos a boa memória interna de 256 GB com a possibilidade de expansão.
O Samsung Galaxy A15 5G é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Samsung Galaxy A15 5G tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em alta definição (Full HD) com uma resolução de 1920x1080 pixels. Muito fino, 8.4 milímetros, o que torna o Samsung Galaxy A15 5G realmente interessante.', 'Samsung-Galaxy-A15-5G.jpg', CURRENT_TIMESTAMP),
('Redmi 13C', 'Redmi', 'Phones', 830, 'O Redmi 13C é um smartphone Android completo, que não tem muito a invejar aos mais avançados dispositivos. Surpreendente é sua tela Touchscreen de 6.74 polegadas, que coloca esse Redmi no topo de sua categoria. A resolução também é alta: 1600x720 pixel. Quanto às funções, no Redmi 13C realmente não falta nada. Começando pelo conectividade Wi-fi e GPS. A transferência de dados e navegação web sao fornecidas pela rede UMTS, mas não suporta tecnologias mais recentes, tais como HSDPA. Enfatizamos a boa memória interna de 128 GB com a possibilidade de expansão.
Este Redmi 13C é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Redmi 13C tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em alta definição (Full HD) com uma resolução de 1920x1080 pixels. Muito fino, 8.1 milímetros, o que torna o Redmi 13C realmente interessante.', 'Redmi-13C.jpg', CURRENT_TIMESTAMP),
('Poco C65', 'Poco', 'Phones', 869, 'O Poco C65 é um smartphone Android completo, que não tem muito a invejar aos mais avançados dispositivos. Surpreendente é sua tela Touchscreen de 6.74 polegadas, que coloca esse Poco no topo de sua categoria. A resolução também é alta: 1600x720 pixel. Quanto às funções, no Poco C65 realmente não falta nada. Começando pelo conectividade Wi-fi e GPS. A transferência de dados e navegação web sao fornecidas pela rede UMTS, mas não suporta tecnologias mais recentes, tais como HSDPA. Enfatizamos a boa memória interna de 128 GB com a possibilidade de expansão.
Este Poco C65 é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Poco C65 tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em alta definição (Full HD) com uma resolução de 1920x1080 pixels. Muito fino, 8.1 milímetros, o que torna o Poco C65 realmente interessante.', 'Poco-C65.jpg', CURRENT_TIMESTAMP),
('Motorola Edge', 'Motorola', 'Phones', 1.979 , 'O Motorola Edge é um smartphone Android de bom nível, ótimo para fotos, que pode satisfazer até o mais exigente dos usuários. Tem uma enorme tela Touchscreen de 6.6 polegadas com uma resolução de 2400x1080 pixel. Sobre as características deste Motorola Edge na verdade não falta nada. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet, além de conectividade Wi-fi e GPS. Tem também leitor multimídia, videoconferência e bluetooth. Enfatizamos a boa memória interna de 256 GB mas sem a possibilidade de expansão.
O Motorola Edge é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Motorola Edge tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em 4K a espantosa resolução de 3840x2160 pixels. Muito fino, 7.6 milímetros, o que torna o Motorola Edge realmente interessante.', 'Motorola-Edge.jpg', CURRENT_TIMESTAMP),
('Samsung Galaxy S23 FE', 'Samsung', 'Phones', 2.699, 'O Samsung Galaxy S23 FE é um smartphone Android avançado e abrangente em todos os pontos de vista com algumas características excelentes. Tem uma grande tela de 6.4 polegadas com uma resolução de 2340x1080 pixels. As funcionalidades oferecidas pelo Samsung Galaxy S23 FE são muitas e inovadoras. Começando pelo 5G que permite a transferência de dados e excelente navegação na internet. Enfatizamos a excelente memória interna de 256 GB mas sem a possibilidade de expansão.
O Samsung Galaxy S23 FE é um produto com poucos concorrentes em termos de multimídia graças à câmera de 50 megapixels que permite ao Samsung Galaxy S23 FE tirar fotos fantásticas com uma resolução de 8165x6124 pixels e gravar vídeos em 8K a espantosa resolução de 7680x4320 pixels. Muito fino, 8.2 milímetros, o que torna o Samsung Galaxy S23 FE realmente interessante.', 'Samsung-Galaxy-S23-FE.jpg', CURRENT_TIMESTAMP),
('Computador Desktop Dell Vostro I1200-M10', 'Dell', 'Computers', 2.589, 'ESPECIFICAÇÕES TÉCNICAS
Cor: Preto
Processador: 12ª Geração de Intel® Core™ i3-12100 (4-core, 8-thread, cache de 12MB, 3.3GHz até 4.3GHz)
Unidade de Estado Sólido SSD de 256GB PCIe NVMe M.2
Placa de vídeo Intel® UHD Graphics 730
Teclado Dell KB216 preto, com fio, em português
Sistema Operacional: Windows 11 Home em Português (Brasil)
Portas: Frente: 2 Portas USB 3.2 Gen 1 Type-A, 2 Portas USB 2.0, Combo Jack (conector para fone de ouvido e microfone combinados) | Portas traseiras: 2 Portas USB 3.2 Gen 1 Type-A, 2 Portas USB 2.0, 1 Entrada RJ-45, 1 Saída de linha, 1 Saída HDMI, 1 Porta de vídeo DisplayPort 1.4
Áudio: Waves MaxxAudio® Pro | Conectividade: Dell Wireless Intel® Wi-Fi 6E 2x2 + Bluetooth | Chipset: Integrado ao processador | 100 - 240 Volts AC (Bivolt) |Altura: 9.3 cm | Largura: 29 cm | Profundidade: 29.3 cm | Peso aproximado: 3.6 Kg | | Conteúdo da embalagem: Computador, Teclado, mouse, cabo de força, manuais e Monitor | Imagens meramente ilustrativas.', 'Desktop-Dell-Vostro-1200-M10.jpg', CURRENT_TIMESTAMP),
('OptiPlex Micro', 'Dell', 'Computers', 2.649, 'processor
13ª Geração Intel® Core™ i3-13100T (4 Núcleos, 12MB, 2.50 GHz to 4.20 GHz, 35 W)
laptop
Windows 11 Home, Português, Inglês, Francês, Espanhol (Compatível com memória 8GB ou inferior)
(A Dell Technologies recomenda o Windows 11 Pro para empresas)
memory
8 GB DDR4 (1x8GB) 3200MT/s
harddrive
SSD de 256GB PCIe NVMe M.2 (Classe 35)
fallbackcolor
OptiPlex Micro com CPU de 35W', 'OptiPlex-Micro.jpg', CURRENT_TIMESTAMP),
('Workstation Precision 3660', 'Dell', 'Computers', 4.999, '
13ª geração Intel® Core™ i5-13500 (14-cores, 20 threads, cache de 24 MB, 2.50 GHz a 4.80 GHz Turbo, 65 W)
laptop
Windows 11 Pro, português (Brasil)
(A Dell Technologies recomenda o Windows 11 Pro para empresas)
videocard
Placa gráfica integrada Intel
memory
16GB DDR5 (2x8G) 4400 MT/s
harddrive
SSD 256 GB PCIe NVMe™ M.2 Classe 35 BCC
fallbackcolor
Precision 3660 Tower with 500W (80 Plus Platinum) PSU, RPL and ADL Compatible', 'workstations-precision-3660.jpg', CURRENT_TIMESTAMP);